/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AdvancedEmailDetectionRequest', 'model/AdvancedUrlDetectionRequest', 'model/PhishingDetectionAdvancedRequest', 'model/PhishingDetectionAdvancedResponse', 'model/PhishingDetectionEmailAdvancedResponse', 'model/PhishingDetectionResponse', 'model/PhishingDetectionTextStringRequest', 'model/PhishingDetectionTextStringResponse', 'model/PhishingDetectionUrlAdvancedResponse', 'model/UnsafeUrlResult', 'api/PhishingDetectionApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AdvancedEmailDetectionRequest'), require('./model/AdvancedUrlDetectionRequest'), require('./model/PhishingDetectionAdvancedRequest'), require('./model/PhishingDetectionAdvancedResponse'), require('./model/PhishingDetectionEmailAdvancedResponse'), require('./model/PhishingDetectionResponse'), require('./model/PhishingDetectionTextStringRequest'), require('./model/PhishingDetectionTextStringResponse'), require('./model/PhishingDetectionUrlAdvancedResponse'), require('./model/UnsafeUrlResult'), require('./api/PhishingDetectionApi'));
  }
}(function(ApiClient, AdvancedEmailDetectionRequest, AdvancedUrlDetectionRequest, PhishingDetectionAdvancedRequest, PhishingDetectionAdvancedResponse, PhishingDetectionEmailAdvancedResponse, PhishingDetectionResponse, PhishingDetectionTextStringRequest, PhishingDetectionTextStringResponse, PhishingDetectionUrlAdvancedResponse, UnsafeUrlResult, PhishingDetectionApi) {
  'use strict';

  /**
   * Easily_and_directly_scan_and_block_phishing_security_threats_in_input_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersivePhishingapiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersivePhishingapiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersivePhishingapiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersivePhishingapiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersivePhishingapiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0.3
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AdvancedEmailDetectionRequest model constructor.
     * @property {module:model/AdvancedEmailDetectionRequest}
     */
    AdvancedEmailDetectionRequest: AdvancedEmailDetectionRequest,
    /**
     * The AdvancedUrlDetectionRequest model constructor.
     * @property {module:model/AdvancedUrlDetectionRequest}
     */
    AdvancedUrlDetectionRequest: AdvancedUrlDetectionRequest,
    /**
     * The PhishingDetectionAdvancedRequest model constructor.
     * @property {module:model/PhishingDetectionAdvancedRequest}
     */
    PhishingDetectionAdvancedRequest: PhishingDetectionAdvancedRequest,
    /**
     * The PhishingDetectionAdvancedResponse model constructor.
     * @property {module:model/PhishingDetectionAdvancedResponse}
     */
    PhishingDetectionAdvancedResponse: PhishingDetectionAdvancedResponse,
    /**
     * The PhishingDetectionEmailAdvancedResponse model constructor.
     * @property {module:model/PhishingDetectionEmailAdvancedResponse}
     */
    PhishingDetectionEmailAdvancedResponse: PhishingDetectionEmailAdvancedResponse,
    /**
     * The PhishingDetectionResponse model constructor.
     * @property {module:model/PhishingDetectionResponse}
     */
    PhishingDetectionResponse: PhishingDetectionResponse,
    /**
     * The PhishingDetectionTextStringRequest model constructor.
     * @property {module:model/PhishingDetectionTextStringRequest}
     */
    PhishingDetectionTextStringRequest: PhishingDetectionTextStringRequest,
    /**
     * The PhishingDetectionTextStringResponse model constructor.
     * @property {module:model/PhishingDetectionTextStringResponse}
     */
    PhishingDetectionTextStringResponse: PhishingDetectionTextStringResponse,
    /**
     * The PhishingDetectionUrlAdvancedResponse model constructor.
     * @property {module:model/PhishingDetectionUrlAdvancedResponse}
     */
    PhishingDetectionUrlAdvancedResponse: PhishingDetectionUrlAdvancedResponse,
    /**
     * The UnsafeUrlResult model constructor.
     * @property {module:model/UnsafeUrlResult}
     */
    UnsafeUrlResult: UnsafeUrlResult,
    /**
     * The PhishingDetectionApi service constructor.
     * @property {module:api/PhishingDetectionApi}
     */
    PhishingDetectionApi: PhishingDetectionApi
  };

  return exports;
}));
