/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersivePhishingapiClient);
  }
}(this, function(expect, CloudmersivePhishingapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AdvancedUrlDetectionRequest', function() {
      beforeEach(function() {
        instance = new CloudmersivePhishingapiClient.AdvancedUrlDetectionRequest();
      });

      it('should create an instance of AdvancedUrlDetectionRequest', function() {
        // TODO: update the code to test AdvancedUrlDetectionRequest
        expect(instance).to.be.a(CloudmersivePhishingapiClient.AdvancedUrlDetectionRequest);
      });

      it('should have the property url (base name: "Url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property customPolicyID (base name: "CustomPolicyID")', function() {
        // TODO: update the code to test the property customPolicyID
        expect(instance).to.have.property('customPolicyID');
        // expect(instance.customPolicyID).to.be(expectedValueLiteral);
      });

    });
  });

}));
