/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersivePhishingapiClient);
  }
}(this, function(expect, CloudmersivePhishingapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PhishingDetectionEmailAdvancedResponse', function() {
      beforeEach(function() {
        instance = new CloudmersivePhishingapiClient.PhishingDetectionEmailAdvancedResponse();
      });

      it('should create an instance of PhishingDetectionEmailAdvancedResponse', function() {
        // TODO: update the code to test PhishingDetectionEmailAdvancedResponse
        expect(instance).to.be.a(CloudmersivePhishingapiClient.PhishingDetectionEmailAdvancedResponse);
      });

      it('should have the property cleanResult (base name: "CleanResult")', function() {
        // TODO: update the code to test the property cleanResult
        expect(instance).to.have.property('cleanResult');
        // expect(instance.cleanResult).to.be(expectedValueLiteral);
      });

      it('should have the property phishingRiskLevel (base name: "PhishingRiskLevel")', function() {
        // TODO: update the code to test the property phishingRiskLevel
        expect(instance).to.have.property('phishingRiskLevel');
        // expect(instance.phishingRiskLevel).to.be(expectedValueLiteral);
      });

      it('should have the property spamRiskLevel (base name: "SpamRiskLevel")', function() {
        // TODO: update the code to test the property spamRiskLevel
        expect(instance).to.have.property('spamRiskLevel');
        // expect(instance.spamRiskLevel).to.be(expectedValueLiteral);
      });

      it('should have the property containsLowReputationSender (base name: "ContainsLowReputationSender")', function() {
        // TODO: update the code to test the property containsLowReputationSender
        expect(instance).to.have.property('containsLowReputationSender');
        // expect(instance.containsLowReputationSender).to.be(expectedValueLiteral);
      });

      it('should have the property containsPhishing (base name: "ContainsPhishing")', function() {
        // TODO: update the code to test the property containsPhishing
        expect(instance).to.have.property('containsPhishing');
        // expect(instance.containsPhishing).to.be(expectedValueLiteral);
      });

      it('should have the property containsSpam (base name: "ContainsSpam")', function() {
        // TODO: update the code to test the property containsSpam
        expect(instance).to.have.property('containsSpam');
        // expect(instance.containsSpam).to.be(expectedValueLiteral);
      });

      it('should have the property containsUnsolicitedSales (base name: "ContainsUnsolicitedSales")', function() {
        // TODO: update the code to test the property containsUnsolicitedSales
        expect(instance).to.have.property('containsUnsolicitedSales');
        // expect(instance.containsUnsolicitedSales).to.be(expectedValueLiteral);
      });

      it('should have the property containsPromotionalContent (base name: "ContainsPromotionalContent")', function() {
        // TODO: update the code to test the property containsPromotionalContent
        expect(instance).to.have.property('containsPromotionalContent');
        // expect(instance.containsPromotionalContent).to.be(expectedValueLiteral);
      });

      it('should have the property containsPhishingAttempt (base name: "ContainsPhishingAttempt")', function() {
        // TODO: update the code to test the property containsPhishingAttempt
        expect(instance).to.have.property('containsPhishingAttempt');
        // expect(instance.containsPhishingAttempt).to.be(expectedValueLiteral);
      });

      it('should have the property analysisRationale (base name: "AnalysisRationale")', function() {
        // TODO: update the code to test the property analysisRationale
        expect(instance).to.have.property('analysisRationale');
        // expect(instance.analysisRationale).to.be(expectedValueLiteral);
      });

    });
  });

}));
