/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersivePhishingapiClient);
  }
}(this, function(expect, CloudmersivePhishingapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PhishingDetectionAdvancedRequest', function() {
      beforeEach(function() {
        instance = new CloudmersivePhishingapiClient.PhishingDetectionAdvancedRequest();
      });

      it('should create an instance of PhishingDetectionAdvancedRequest', function() {
        // TODO: update the code to test PhishingDetectionAdvancedRequest
        expect(instance).to.be.a(CloudmersivePhishingapiClient.PhishingDetectionAdvancedRequest);
      });

      it('should have the property inputString (base name: "InputString")', function() {
        // TODO: update the code to test the property inputString
        expect(instance).to.have.property('inputString');
        // expect(instance.inputString).to.be(expectedValueLiteral);
      });

      it('should have the property textType (base name: "TextType")', function() {
        // TODO: update the code to test the property textType
        expect(instance).to.have.property('textType');
        // expect(instance.textType).to.be(expectedValueLiteral);
      });

      it('should have the property model (base name: "Model")', function() {
        // TODO: update the code to test the property model
        expect(instance).to.have.property('model');
        // expect(instance.model).to.be(expectedValueLiteral);
      });

      it('should have the property allowUnsolicitedSales (base name: "AllowUnsolicitedSales")', function() {
        // TODO: update the code to test the property allowUnsolicitedSales
        expect(instance).to.have.property('allowUnsolicitedSales');
        // expect(instance.allowUnsolicitedSales).to.be(expectedValueLiteral);
      });

      it('should have the property allowPromotionalContent (base name: "AllowPromotionalContent")', function() {
        // TODO: update the code to test the property allowPromotionalContent
        expect(instance).to.have.property('allowPromotionalContent');
        // expect(instance.allowPromotionalContent).to.be(expectedValueLiteral);
      });

      it('should have the property allowWebUrls (base name: "AllowWebUrls")', function() {
        // TODO: update the code to test the property allowWebUrls
        expect(instance).to.have.property('allowWebUrls');
        // expect(instance.allowWebUrls).to.be(expectedValueLiteral);
      });

      it('should have the property allowPhoneNumbers (base name: "AllowPhoneNumbers")', function() {
        // TODO: update the code to test the property allowPhoneNumbers
        expect(instance).to.have.property('allowPhoneNumbers');
        // expect(instance.allowPhoneNumbers).to.be(expectedValueLiteral);
      });

      it('should have the property allowEmailAddresses (base name: "AllowEmailAddresses")', function() {
        // TODO: update the code to test the property allowEmailAddresses
        expect(instance).to.have.property('allowEmailAddresses');
        // expect(instance.allowEmailAddresses).to.be(expectedValueLiteral);
      });

      it('should have the property provideUrlAnalysis (base name: "ProvideUrlAnalysis")', function() {
        // TODO: update the code to test the property provideUrlAnalysis
        expect(instance).to.have.property('provideUrlAnalysis');
        // expect(instance.provideUrlAnalysis).to.be(expectedValueLiteral);
      });

      it('should have the property customPolicyID (base name: "CustomPolicyID")', function() {
        // TODO: update the code to test the property customPolicyID
        expect(instance).to.have.property('customPolicyID');
        // expect(instance.customPolicyID).to.be(expectedValueLiteral);
      });

      it('should have the property provideAnalysisRationale (base name: "ProvideAnalysisRationale")', function() {
        // TODO: update the code to test the property provideAnalysisRationale
        expect(instance).to.have.property('provideAnalysisRationale');
        // expect(instance.provideAnalysisRationale).to.be(expectedValueLiteral);
      });

      it('should have the property fromName (base name: "FromName")', function() {
        // TODO: update the code to test the property fromName
        expect(instance).to.have.property('fromName');
        // expect(instance.fromName).to.be(expectedValueLiteral);
      });

      it('should have the property toName (base name: "ToName")', function() {
        // TODO: update the code to test the property toName
        expect(instance).to.have.property('toName');
        // expect(instance.toName).to.be(expectedValueLiteral);
      });

      it('should have the property fromPhoneNumber (base name: "FromPhoneNumber")', function() {
        // TODO: update the code to test the property fromPhoneNumber
        expect(instance).to.have.property('fromPhoneNumber');
        // expect(instance.fromPhoneNumber).to.be(expectedValueLiteral);
      });

      it('should have the property toPhoneNumber (base name: "ToPhoneNumber")', function() {
        // TODO: update the code to test the property toPhoneNumber
        expect(instance).to.have.property('toPhoneNumber');
        // expect(instance.toPhoneNumber).to.be(expectedValueLiteral);
      });

      it('should have the property fromEmailAddress (base name: "FromEmailAddress")', function() {
        // TODO: update the code to test the property fromEmailAddress
        expect(instance).to.have.property('fromEmailAddress');
        // expect(instance.fromEmailAddress).to.be(expectedValueLiteral);
      });

      it('should have the property toEmailAddress (base name: "ToEmailAddress")', function() {
        // TODO: update the code to test the property toEmailAddress
        expect(instance).to.have.property('toEmailAddress');
        // expect(instance.toEmailAddress).to.be(expectedValueLiteral);
      });

    });
  });

}));
