/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersivePhishingapiClient);
  }
}(this, function(expect, CloudmersivePhishingapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PhishingDetectionTextStringRequest', function() {
      beforeEach(function() {
        instance = new CloudmersivePhishingapiClient.PhishingDetectionTextStringRequest();
      });

      it('should create an instance of PhishingDetectionTextStringRequest', function() {
        // TODO: update the code to test PhishingDetectionTextStringRequest
        expect(instance).to.be.a(CloudmersivePhishingapiClient.PhishingDetectionTextStringRequest);
      });

      it('should have the property inputString (base name: "InputString")', function() {
        // TODO: update the code to test the property inputString
        expect(instance).to.have.property('inputString');
        // expect(instance.inputString).to.be(expectedValueLiteral);
      });

      it('should have the property model (base name: "Model")', function() {
        // TODO: update the code to test the property model
        expect(instance).to.have.property('model');
        // expect(instance.model).to.be(expectedValueLiteral);
      });

      it('should have the property provideAnalysisRationale (base name: "ProvideAnalysisRationale")', function() {
        // TODO: update the code to test the property provideAnalysisRationale
        expect(instance).to.have.property('provideAnalysisRationale');
        // expect(instance.provideAnalysisRationale).to.be(expectedValueLiteral);
      });

    });
  });

}));
