/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersivePhishingapiClient);
  }
}(this, function(expect, CloudmersivePhishingapiClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UnsafeUrlResult', function() {
      beforeEach(function() {
        instance = new CloudmersivePhishingapiClient.UnsafeUrlResult();
      });

      it('should create an instance of UnsafeUrlResult', function() {
        // TODO: update the code to test UnsafeUrlResult
        expect(instance).to.be.a(CloudmersivePhishingapiClient.UnsafeUrlResult);
      });

      it('should have the property url (base name: "Url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property cleanResult (base name: "CleanResult")', function() {
        // TODO: update the code to test the property cleanResult
        expect(instance).to.have.property('cleanResult');
        // expect(instance.cleanResult).to.be(expectedValueLiteral);
      });

      it('should have the property isSsrfThreat (base name: "IsSsrfThreat")', function() {
        // TODO: update the code to test the property isSsrfThreat
        expect(instance).to.have.property('isSsrfThreat');
        // expect(instance.isSsrfThreat).to.be(expectedValueLiteral);
      });

      it('should have the property containsPhishing (base name: "ContainsPhishing")', function() {
        // TODO: update the code to test the property containsPhishing
        expect(instance).to.have.property('containsPhishing');
        // expect(instance.containsPhishing).to.be(expectedValueLiteral);
      });

      it('should have the property containsPhishingAttempt (base name: "ContainsPhishingAttempt")', function() {
        // TODO: update the code to test the property containsPhishingAttempt
        expect(instance).to.have.property('containsPhishingAttempt');
        // expect(instance.containsPhishingAttempt).to.be(expectedValueLiteral);
      });

    });
  });

}));
