/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.AdvancedUrlDetectionRequest = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The AdvancedUrlDetectionRequest model module.
   * @module model/AdvancedUrlDetectionRequest
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>AdvancedUrlDetectionRequest</code>.
   * Request to detect phishing from a URL
   * @alias module:model/AdvancedUrlDetectionRequest
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AdvancedUrlDetectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdvancedUrlDetectionRequest} obj Optional instance to populate.
   * @return {module:model/AdvancedUrlDetectionRequest} The populated <code>AdvancedUrlDetectionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('Url'))
        obj.url = ApiClient.convertToType(data['Url'], 'String');
      if (data.hasOwnProperty('CustomPolicyID'))
        obj.customPolicyID = ApiClient.convertToType(data['CustomPolicyID'], 'String');
    }
    return obj;
  }

  /**
   * URL to check for phishing
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
   * @member {String} customPolicyID
   */
  exports.prototype.customPolicyID = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
