/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.AdvancedEmailDetectionRequest = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The AdvancedEmailDetectionRequest model module.
   * @module model/AdvancedEmailDetectionRequest
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>AdvancedEmailDetectionRequest</code>.
   * Request to detect phishing from an email
   * @alias module:model/AdvancedEmailDetectionRequest
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AdvancedEmailDetectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdvancedEmailDetectionRequest} obj Optional instance to populate.
   * @return {module:model/AdvancedEmailDetectionRequest} The populated <code>AdvancedEmailDetectionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('FromEmailAddress'))
        obj.fromEmailAddress = ApiClient.convertToType(data['FromEmailAddress'], 'String');
      if (data.hasOwnProperty('ToEmailAddress'))
        obj.toEmailAddress = ApiClient.convertToType(data['ToEmailAddress'], 'String');
      if (data.hasOwnProperty('Subject'))
        obj.subject = ApiClient.convertToType(data['Subject'], 'String');
      if (data.hasOwnProperty('HtmlBody'))
        obj.htmlBody = ApiClient.convertToType(data['HtmlBody'], 'String');
      if (data.hasOwnProperty('AllowLowReputationSenders'))
        obj.allowLowReputationSenders = ApiClient.convertToType(data['AllowLowReputationSenders'], 'Boolean');
      if (data.hasOwnProperty('AllowSanctioned'))
        obj.allowSanctioned = ApiClient.convertToType(data['AllowSanctioned'], 'Boolean');
      if (data.hasOwnProperty('CustomPolicyID'))
        obj.customPolicyID = ApiClient.convertToType(data['CustomPolicyID'], 'String');
      if (data.hasOwnProperty('InputEmailFile'))
        obj.inputEmailFile = ApiClient.convertToType(data['InputEmailFile'], 'Blob');
    }
    return obj;
  }

  /**
   * Email address of the sender
   * @member {String} fromEmailAddress
   */
  exports.prototype.fromEmailAddress = undefined;

  /**
   * Email address of the recipient
   * @member {String} toEmailAddress
   */
  exports.prototype.toEmailAddress = undefined;

  /**
   * Subject of the email
   * @member {String} subject
   */
  exports.prototype.subject = undefined;

  /**
   * Body of the email in HTML, or text
   * @member {String} htmlBody
   */
  exports.prototype.htmlBody = undefined;

  /**
   * Allow email from low reputation senders and domains
   * @member {Boolean} allowLowReputationSenders
   */
  exports.prototype.allowLowReputationSenders = undefined;

  /**
   * True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default)
   * @member {Boolean} allowSanctioned
   */
  exports.prototype.allowSanctioned = undefined;

  /**
   * Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
   * @member {String} customPolicyID
   */
  exports.prototype.customPolicyID = undefined;

  /**
   * Optional: Input email file bytes (EML, PDF, etc.).  If not provided, HtmlBody will be used instead.
   * @member {Blob} inputEmailFile
   */
  exports.prototype.inputEmailFile = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
