/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.PhishingDetectionAdvancedRequest = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The PhishingDetectionAdvancedRequest model module.
   * @module model/PhishingDetectionAdvancedRequest
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>PhishingDetectionAdvancedRequest</code>.
   * AI advanced phishing detection request
   * @alias module:model/PhishingDetectionAdvancedRequest
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PhishingDetectionAdvancedRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhishingDetectionAdvancedRequest} obj Optional instance to populate.
   * @return {module:model/PhishingDetectionAdvancedRequest} The populated <code>PhishingDetectionAdvancedRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('InputString'))
        obj.inputString = ApiClient.convertToType(data['InputString'], 'String');
      if (data.hasOwnProperty('TextType'))
        obj.textType = ApiClient.convertToType(data['TextType'], 'String');
      if (data.hasOwnProperty('Model'))
        obj.model = ApiClient.convertToType(data['Model'], 'String');
      if (data.hasOwnProperty('AllowUnsolicitedSales'))
        obj.allowUnsolicitedSales = ApiClient.convertToType(data['AllowUnsolicitedSales'], 'Boolean');
      if (data.hasOwnProperty('AllowPromotionalContent'))
        obj.allowPromotionalContent = ApiClient.convertToType(data['AllowPromotionalContent'], 'Boolean');
      if (data.hasOwnProperty('AllowWebUrls'))
        obj.allowWebUrls = ApiClient.convertToType(data['AllowWebUrls'], 'Boolean');
      if (data.hasOwnProperty('AllowPhoneNumbers'))
        obj.allowPhoneNumbers = ApiClient.convertToType(data['AllowPhoneNumbers'], 'Boolean');
      if (data.hasOwnProperty('AllowEmailAddresses'))
        obj.allowEmailAddresses = ApiClient.convertToType(data['AllowEmailAddresses'], 'Boolean');
      if (data.hasOwnProperty('ProvideUrlAnalysis'))
        obj.provideUrlAnalysis = ApiClient.convertToType(data['ProvideUrlAnalysis'], 'Boolean');
      if (data.hasOwnProperty('CustomPolicyID'))
        obj.customPolicyID = ApiClient.convertToType(data['CustomPolicyID'], 'String');
      if (data.hasOwnProperty('ProvideAnalysisRationale'))
        obj.provideAnalysisRationale = ApiClient.convertToType(data['ProvideAnalysisRationale'], 'Boolean');
      if (data.hasOwnProperty('FromName'))
        obj.fromName = ApiClient.convertToType(data['FromName'], 'String');
      if (data.hasOwnProperty('ToName'))
        obj.toName = ApiClient.convertToType(data['ToName'], 'String');
      if (data.hasOwnProperty('FromPhoneNumber'))
        obj.fromPhoneNumber = ApiClient.convertToType(data['FromPhoneNumber'], 'String');
      if (data.hasOwnProperty('ToPhoneNumber'))
        obj.toPhoneNumber = ApiClient.convertToType(data['ToPhoneNumber'], 'String');
      if (data.hasOwnProperty('FromEmailAddress'))
        obj.fromEmailAddress = ApiClient.convertToType(data['FromEmailAddress'], 'String');
      if (data.hasOwnProperty('ToEmailAddress'))
        obj.toEmailAddress = ApiClient.convertToType(data['ToEmailAddress'], 'String');
    }
    return obj;
  }

  /**
   * Input text string to detect phishing against
   * @member {String} inputString
   */
  exports.prototype.inputString = undefined;

  /**
   * Optional: Type of text being analyzed. Must be one of: \"TextMessage\", \"UserMessage\", \"SalesLead\", \"EmailMessage\", \"SupportCase\", \"AppMessage\", \"Other\".
   * @member {String} textType
   */
  exports.prototype.textType = undefined;

  /**
   * Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
   * @member {String} model
   */
  exports.prototype.model = undefined;

  /**
   * Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.
   * @member {Boolean} allowUnsolicitedSales
   */
  exports.prototype.allowUnsolicitedSales = undefined;

  /**
   * Optional: True if promotional content should be allowed, false otherwise. Defaults to true.
   * @member {Boolean} allowPromotionalContent
   */
  exports.prototype.allowPromotionalContent = undefined;

  /**
   * Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.
   * @member {Boolean} allowWebUrls
   */
  exports.prototype.allowWebUrls = undefined;

  /**
   * Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.
   * @member {Boolean} allowPhoneNumbers
   */
  exports.prototype.allowPhoneNumbers = undefined;

  /**
   * Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \"danny at somedomaine [DOT] com\") will be flagged as not clean.
   * @member {Boolean} allowEmailAddresses
   */
  exports.prototype.allowEmailAddresses = undefined;

  /**
   * Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.
   * @member {Boolean} provideUrlAnalysis
   */
  exports.prototype.provideUrlAnalysis = undefined;

  /**
   * Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
   * @member {String} customPolicyID
   */
  exports.prototype.customPolicyID = undefined;

  /**
   * Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
   * @member {Boolean} provideAnalysisRationale
   */
  exports.prototype.provideAnalysisRationale = undefined;

  /**
   * Optional: Name of the sender
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * Optional: Name of the recipient
   * @member {String} toName
   */
  exports.prototype.toName = undefined;

  /**
   * Optional: Phone number of the sender
   * @member {String} fromPhoneNumber
   */
  exports.prototype.fromPhoneNumber = undefined;

  /**
   * Optional: Phone number of the recipient
   * @member {String} toPhoneNumber
   */
  exports.prototype.toPhoneNumber = undefined;

  /**
   * Optional: Email address of the sender
   * @member {String} fromEmailAddress
   */
  exports.prototype.fromEmailAddress = undefined;

  /**
   * Optional: Email address of the recipient
   * @member {String} toEmailAddress
   */
  exports.prototype.toEmailAddress = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
