/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.PhishingDetectionUrlAdvancedResponse = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The PhishingDetectionUrlAdvancedResponse model module.
   * @module model/PhishingDetectionUrlAdvancedResponse
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>PhishingDetectionUrlAdvancedResponse</code>.
   * Result of detecting phishing from a URL using AI
   * @alias module:model/PhishingDetectionUrlAdvancedResponse
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PhishingDetectionUrlAdvancedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhishingDetectionUrlAdvancedResponse} obj Optional instance to populate.
   * @return {module:model/PhishingDetectionUrlAdvancedResponse} The populated <code>PhishingDetectionUrlAdvancedResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('CleanResult'))
        obj.cleanResult = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      if (data.hasOwnProperty('PhishingRiskLevel'))
        obj.phishingRiskLevel = ApiClient.convertToType(data['PhishingRiskLevel'], 'Number');
      if (data.hasOwnProperty('IsSsrfThreat'))
        obj.isSsrfThreat = ApiClient.convertToType(data['IsSsrfThreat'], 'Boolean');
      if (data.hasOwnProperty('ContainsPhishing'))
        obj.containsPhishing = ApiClient.convertToType(data['ContainsPhishing'], 'Boolean');
      if (data.hasOwnProperty('ContainsUnsolicitedSales'))
        obj.containsUnsolicitedSales = ApiClient.convertToType(data['ContainsUnsolicitedSales'], 'Boolean');
      if (data.hasOwnProperty('ContainsPromotionalContent'))
        obj.containsPromotionalContent = ApiClient.convertToType(data['ContainsPromotionalContent'], 'Boolean');
      if (data.hasOwnProperty('ContainsPhishingAttempt'))
        obj.containsPhishingAttempt = ApiClient.convertToType(data['ContainsPhishingAttempt'], 'Boolean');
      if (data.hasOwnProperty('AnalysisRationale'))
        obj.analysisRationale = ApiClient.convertToType(data['AnalysisRationale'], 'String');
    }
    return obj;
  }

  /**
   * True if the result is not phishing (clean), and false otherwise
   * @member {Boolean} cleanResult
   */
  exports.prototype.cleanResult = undefined;

  /**
   * Overall phishing risk level between 0.0 and 1.0
   * @member {Number} phishingRiskLevel
   */
  exports.prototype.phishingRiskLevel = undefined;

  /**
   * True if the URL is an SSRF threat
   * @member {Boolean} isSsrfThreat
   */
  exports.prototype.isSsrfThreat = undefined;

  /**
   * True if the URL contains phishing threat risks, false otherwise
   * @member {Boolean} containsPhishing
   */
  exports.prototype.containsPhishing = undefined;

  /**
   * True if the URL contains unsolicited sales, false otherwise
   * @member {Boolean} containsUnsolicitedSales
   */
  exports.prototype.containsUnsolicitedSales = undefined;

  /**
   * True if the URL contains promotional content, false otherwise
   * @member {Boolean} containsPromotionalContent
   */
  exports.prototype.containsPromotionalContent = undefined;

  /**
   * True if the URL contains a phishing attempt, false otherwise
   * @member {Boolean} containsPhishingAttempt
   */
  exports.prototype.containsPhishingAttempt = undefined;

  /**
   * Rationale for why the conclusion was formed
   * @member {String} analysisRationale
   */
  exports.prototype.analysisRationale = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
