/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject', 'model/UnsafeUrlResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'), require('./UnsafeUrlResult'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.PhishingDetectionAdvancedResponse = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject, root.CloudmersivePhishingapiClient.UnsafeUrlResult);
  }
}(this, function(ApiClient, ModelObject, UnsafeUrlResult) {
  'use strict';

  /**
   * The PhishingDetectionAdvancedResponse model module.
   * @module model/PhishingDetectionAdvancedResponse
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>PhishingDetectionAdvancedResponse</code>.
   * Result of detecting phishing using AI
   * @alias module:model/PhishingDetectionAdvancedResponse
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PhishingDetectionAdvancedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhishingDetectionAdvancedResponse} obj Optional instance to populate.
   * @return {module:model/PhishingDetectionAdvancedResponse} The populated <code>PhishingDetectionAdvancedResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('CleanResult'))
        obj.cleanResult = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      if (data.hasOwnProperty('ContainsPhishing'))
        obj.containsPhishing = ApiClient.convertToType(data['ContainsPhishing'], 'Boolean');
      if (data.hasOwnProperty('ContainsUnsolicitedSales'))
        obj.containsUnsolicitedSales = ApiClient.convertToType(data['ContainsUnsolicitedSales'], 'Boolean');
      if (data.hasOwnProperty('ContainsPromotionalContent'))
        obj.containsPromotionalContent = ApiClient.convertToType(data['ContainsPromotionalContent'], 'Boolean');
      if (data.hasOwnProperty('ContainsWebUrls'))
        obj.containsWebUrls = ApiClient.convertToType(data['ContainsWebUrls'], 'Boolean');
      if (data.hasOwnProperty('ContainsPhoneNumbers'))
        obj.containsPhoneNumbers = ApiClient.convertToType(data['ContainsPhoneNumbers'], 'Boolean');
      if (data.hasOwnProperty('ContainsEmailAddresses'))
        obj.containsEmailAddresses = ApiClient.convertToType(data['ContainsEmailAddresses'], 'Boolean');
      if (data.hasOwnProperty('ConfidenceLevel'))
        obj.confidenceLevel = ApiClient.convertToType(data['ConfidenceLevel'], 'Number');
      if (data.hasOwnProperty('AnalysisRationale'))
        obj.analysisRationale = ApiClient.convertToType(data['AnalysisRationale'], 'String');
      if (data.hasOwnProperty('UnsafeUrls'))
        obj.unsafeUrls = ApiClient.convertToType(data['UnsafeUrls'], [UnsafeUrlResult]);
    }
    return obj;
  }

  /**
   * True if the result is not phishing (clean), and false otherwise
   * @member {Boolean} cleanResult
   */
  exports.prototype.cleanResult = undefined;

  /**
   * True if the input text contains a phishing attempt, false otherwise
   * @member {Boolean} containsPhishing
   */
  exports.prototype.containsPhishing = undefined;

  /**
   * True if the input text contains unsolicited sales, false otherwise
   * @member {Boolean} containsUnsolicitedSales
   */
  exports.prototype.containsUnsolicitedSales = undefined;

  /**
   * True if the input text contains promotional content, false otherwise
   * @member {Boolean} containsPromotionalContent
   */
  exports.prototype.containsPromotionalContent = undefined;

  /**
   * True if the input text contains web URLs, including homoglyph URLs and spaced-out URL workarounds
   * @member {Boolean} containsWebUrls
   */
  exports.prototype.containsWebUrls = undefined;

  /**
   * True if the input text contains phone numbers, including homoglyph digits and spaced-out or spelled-out workarounds
   * @member {Boolean} containsPhoneNumbers
   */
  exports.prototype.containsPhoneNumbers = undefined;

  /**
   * True if the input text contains email addresses, including homoglyph characters and obfuscated workarounds
   * @member {Boolean} containsEmailAddresses
   */
  exports.prototype.containsEmailAddresses = undefined;

  /**
   * Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence
   * @member {Number} confidenceLevel
   */
  exports.prototype.confidenceLevel = undefined;

  /**
   * Rationale for why the conclusion was formed
   * @member {String} analysisRationale
   */
  exports.prototype.analysisRationale = undefined;

  /**
   * URLs detected in the input text that were analyzed and found to be unsafe. Only populated when ProvideUrlAnalysis is true and URLs are detected.
   * @member {Array.<module:model/UnsafeUrlResult>} unsafeUrls
   */
  exports.prototype.unsafeUrls = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
