/*
 * phishingapi
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.46
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelObject'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersivePhishingapiClient) {
      root.CloudmersivePhishingapiClient = {};
    }
    root.CloudmersivePhishingapiClient.PhishingDetectionTextStringResponse = factory(root.CloudmersivePhishingapiClient.ApiClient, root.CloudmersivePhishingapiClient.ModelObject);
  }
}(this, function(ApiClient, ModelObject) {
  'use strict';

  /**
   * The PhishingDetectionTextStringResponse model module.
   * @module model/PhishingDetectionTextStringResponse
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>PhishingDetectionTextStringResponse</code>.
   * Result of detecting phishing using AI for basic text string analysis
   * @alias module:model/PhishingDetectionTextStringResponse
   * @class
   * @extends Object
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PhishingDetectionTextStringResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhishingDetectionTextStringResponse} obj Optional instance to populate.
   * @return {module:model/PhishingDetectionTextStringResponse} The populated <code>PhishingDetectionTextStringResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ModelObject');
      if (data.hasOwnProperty('CleanResult'))
        obj.cleanResult = ApiClient.convertToType(data['CleanResult'], 'Boolean');
      if (data.hasOwnProperty('ConfidenceLevel'))
        obj.confidenceLevel = ApiClient.convertToType(data['ConfidenceLevel'], 'Number');
      if (data.hasOwnProperty('AnalysisRationale'))
        obj.analysisRationale = ApiClient.convertToType(data['AnalysisRationale'], 'String');
    }
    return obj;
  }

  /**
   * True if the result is not phishing (clean), and false otherwise
   * @member {Boolean} cleanResult
   */
  exports.prototype.cleanResult = undefined;

  /**
   * Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence
   * @member {Number} confidenceLevel
   */
  exports.prototype.confidenceLevel = undefined;

  /**
   * Rationale for why the conclusion was formed
   * @member {String} analysisRationale
   */
  exports.prototype.analysisRationale = undefined;

  exports.prototype.additionalProperties = new Map();

  return exports;

}));
